package Syntax_Languages;

use warnings;
use strict;


# Standard selected language.
our $Selected = 'Android Logcat';


### Hash of all available languages.
our %Langs = (
	# Language name			# (De)activated?
	'.desktop'				=> 0,
	'4GL'					=> 0,
	'4GL-PER'				=> 0,
	'ABC'					=> 0,
	'AHDL'					=> 0,
	'ANSI C89'				=> 0,
	'ASP'					=> 0,
	'AVR Assembler'				=> 0,
	'AWK'					=> 0,
	'Ada'					=> 0,
        'Android Logcat'                                => 1,
	'Ansys'					=> 0,
	'Apache Configuration'				=> 1,
	'Asm6502'				=> 0,
	'Bash'						=> 1,
	'BibTeX'				=> 0,
	'C'						=> 1,
	'C#'						=> 1,
	'C++'						=> 1,
	'CGiS'					=> 0,
	'CMake'						=> 1,
	'CSS'						=> 1,
	'CUE Sheet'				=> 0,
	'Cg'					=> 0,
	'ChangeLog'					=> 1,
	'Cisco'					=> 0,
	'Clipper'				=> 0,
	'ColdFusion'				=> 0,
	'Common Lisp'				=> 0,
	'Component-Pascal'			=> 0,
	'D'					=> 0,
	'Debian Changelog'				=> 1,
	'Debian Control'			=> 0,
	'Diff'						=> 1,
	'Doxygen'					=> 1,
	'E Language'				=> 0,
	'Eiffel'				=> 0,
	'Email'					=> 0,
	'Euphoria'				=> 0,
	'Fortran'				=> 0,
	'FreeBASIC'				=> 0,
	'GDL'					=> 0,
	'GLSL'					=> 0,
	'GNU Assembler'					=> 1,
	'GNU Gettext'				=> 0,
	'HTML'						=> 1,
	'Haskell'				=> 0,
	'IDL'					=> 0,
	'ILERPG'				=> 0,
	'INI Files'					=> 1,
	'Inform'				=> 0,
	'Intel x86 (NASM)'			=> 0,
	'JSP'						=> 1,
	'Java'						=> 1,
	'JavaScript'					=> 1,
	'Javadoc'				=> 0,
	'KBasic'				=> 0,
	'Kate File Template'				=> 1,
	'LDIF'					=> 0,
	'LPC'					=> 0,
	'LaTeX'					=> 0,
	'Lex/Flex'				=> 0,
	'LilyPond'				=> 0,
	'Literate Haskell'			=> 0,
	'Lua'						=> 1,
	'M3U'					=> 0,
	'MAB-DB'				=> 0,
	'MIPS Assembler'			=> 0,
	'Makefile'					=> 1,
	'Mason'					=> 0,
	'Matlab'				=> 0,
	'Modula-2'				=> 0,
	'Music Publisher'			=> 0,
	'Octave'				=> 0,
	'Plain'						=> 1,
	'PHP (HTML)'					=> 1,
	'POV-Ray'				=> 0,
	'Pascal'					=> 1,
	'Perl'						=> 1,
	'PicAsm'					=> 1,
	'Pike'					=> 0,
	'PostScript'				=> 0,
	'Prolog'				=> 0,
	'PureBasic'				=> 0,
	'Python'					=> 1,
	'Quake Script'				=> 0,
	'R Script'				=> 0,
	'REXX'					=> 0,
	'RPM Spec'				=> 0,
	'RSI IDL'				=> 0,
	'RenderMan RIB'			=> 0,
	'Ruby'						=> 1,
	'SGML'					=> 0,
	'SML'					=> 0,
	'SQL'						=> 1,
	'SQL (MySQL)'					=> 1,
	'SQL (PostgreSQL)'				=> 1,
	'Sather'				=> 0,
	'Scheme'				=> 0,
	'Sieve'					=> 0,
	'Spice'					=> 0,
	'Stata'					=> 0,
	'TI Basic'				=> 0,
	'TaskJuggler'				=> 0,
	'Tcl/Tk'				=> 0,
	'UnrealScript'				=> 0,
	'VHDL'					=> 0,
	'VRML'					=> 0,
	'Velocity'				=> 0,
	'Verilog'				=> 0,
	'WINE Config'				=> 0,
	'Wikimedia'					=> 1,
	'XML'						=> 1,
	'XML (Debug)'				=> 0,
	'Yacc/Bison'				=> 0,
	'de_DE'					=> 0,
	'en_EN'					=> 0,
	'ferite'				=> 0,
	'nl'					=> 0,
	'progress'				=> 0,
	'scilab'				=> 0,
	'txt2tags'				=> 0,
	'x.org Configuration'			=> 0,
	'xHarbour'				=> 0,
	'xslt'					=> 0,
	'yacas'					=> 0
);

1;
